"""code

Revision ID: 1a7bd17fe65f
Revises: e5b387ee48d1
Create Date: 2019-04-21 11:13:30.124489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7bd17fe65f'
down_revision = 'e5b387ee48d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role1', sa.Column('code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role1', 'code')
    # ### end Alembic commands ###
