"""notic

Revision ID: 49b4f1838f35
Revises: 1a7bd17fe65f
Create Date: 2019-04-29 16:39:35.701403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b4f1838f35'
down_revision = '1a7bd17fe65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role1', sa.Column('last_comment_read_time', sa.DATETIME(), nullable=True))
    op.add_column('role1', sa.Column('last_follow_read_time', sa.DATETIME(), nullable=True))
    op.add_column('role1', sa.Column('last_like_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role1', 'last_like_read_time')
    op.drop_column('role1', 'last_follow_read_time')
    op.drop_column('role1', 'last_comment_read_time')
    # ### end Alembic commands ###
