"""nnn

Revision ID: 85819af87e55
Revises: c42fc66da8bb
Create Date: 2019-05-06 01:39:22.942477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85819af87e55'
down_revision = 'c42fc66da8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role1', sa.Column('last_comment_like_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role1', 'last_comment_like_time')
    # ### end Alembic commands ###
