"""mp_notice_2

Revision ID: c42fc66da8bb
Revises: cf266bf19ef3
Create Date: 2019-05-04 23:00:59.728298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42fc66da8bb'
down_revision = 'cf266bf19ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likecomment_ibfk_1', 'likecomment', type_='foreignkey')
    op.create_foreign_key(None, 'likecomment', 'comments1', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likecomment', type_='foreignkey')
    op.create_foreign_key('likecomment_ibfk_1', 'likecomment', 'article1', ['comment_id'], ['id'])
    # ### end Alembic commands ###
