"""avatar_1

Revision ID: e5b387ee48d1
Revises: 
Create Date: 2019-04-19 00:51:54.771991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b387ee48d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role1', sa.Column('default_avatar', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role1', 'default_avatar')
    # ### end Alembic commands ###
